# Generated by Django 5.1.2 on 2024-10-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=11)),
                ('createddate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField(choices=[(1, 'good'), (2, 'moderate'), (3, 'poor'), (4, 'terrible')])),
                ('question2', models.IntegerField(choices=[(1, 'good'), (2, 'moderate'), (3, 'poor'), (4, 'terrible')])),
                ('idea', models.TextField()),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.client')),
            ],
        ),
    ]
