# Generated by Django 5.1.2 on 2024-10-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0002_alter_opinion_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='question1',
            field=models.IntegerField(choices=[('good', 1), (2, 'moderate'), (3, 'poor'), (4, 'terrible')]),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='question2',
            field=models.IntegerField(choices=[('good', 1), (2, 'moderate'), (3, 'poor'), (4, 'terrible')]),
        ),
    ]
